--
-- PostgreSQL database dump
--

\restrict XkengiqWpDyqRzZ3Va3xt17OY3FeqVChr9wi7rChLr2KjHKj7KtGL6lX3ErSuj5

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Booking" (
    "ID" bigint NOT NULL,
    "SlotId" bigint NOT NULL,
    "CustomerName" character varying(200) NOT NULL,
    "Status" integer NOT NULL,
    "customerEmail" character varying(200)
);


ALTER TABLE public."Booking" OWNER TO postgres;

--
-- Name: Booking_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Booking" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Booking_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Slots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Slots" (
    "ID" bigint NOT NULL,
    "startsAt" timestamp with time zone NOT NULL,
    "endsAt" timestamp with time zone NOT NULL,
    "Code" character varying NOT NULL
);


ALTER TABLE public."Slots" OWNER TO postgres;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Booking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Booking" ("ID", "SlotId", "CustomerName", "Status", "customerEmail") FROM stdin;
\.


--
-- Data for Name: Slots; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Slots" ("ID", "startsAt", "endsAt", "Code") FROM stdin;
1	2030-01-15 12:00:00+03	2030-01-15 12:30:00+03	A-6542
2	2030-01-15 13:00:00+03	2030-01-15 13:30:00+03	A-6544
3	2030-01-15 14:00:00+03	2030-01-15 14:30:00+03	A-6540
4	2030-01-15 16:00:00+03	2030-01-15 16:30:00+03	A-6546
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260927122210_InitialCreate	10.0.12
\.


--
-- Name: Booking_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Booking_ID_seq"', 22, true);


--
-- Name: Booking Booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Booking"
    ADD CONSTRAINT "Booking_pkey" PRIMARY KEY ("ID");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: Slots Slots_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Slots"
    ADD CONSTRAINT "Slots_pkey" PRIMARY KEY ("ID");


--
-- Name: IX_Bookings_SlotId_Active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Bookings_SlotId_Active" ON public."Booking" USING btree ("SlotId") WHERE ("Status" = 0);


--
-- PostgreSQL database dump complete
--

\unrestrict XkengiqWpDyqRzZ3Va3xt17OY3FeqVChr9wi7rChLr2KjHKj7KtGL6lX3ErSuj5

